version: '3.9'

services:
    tomcat:
        image: tomcat
        volumes:
            -   ./libTomcat:/usr/local/tomcat/lib
            -   ./target:/usr/local/tomcat/webapps/
        ports:
            - "8080:8080"

    postgres_TP1:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: pwd
            POSTGRES_USER: user