version: '3.2'

services:
  master:
    container_name: hadoop-master
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    tty: true
    stdin_open: true
    networks:
      - hadoop
    ports:
      - '50070:50070'
      - '8088:8088'
      - '707'
  slave1:
    container_name: hadoop-slave1
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    tty: true
    stdin_open: true
    networks:
      - hadoop
    ports:
      - '8042:8042'
    depends_on:
      - master
  slave2:
    container_name: hadoop-slave2
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    tty: true
    stdin_open: true
    networks:
      - hadoop
    ports:
      - '8041:8042'
    depends_on:
      - master
networks:
  hadoop:
    driver: bridge